Repository Syncleus/aparapi, pull requests merged in 2018-04, with the labels that each got.

#80 Update: Add support for Local arguments in kernel functions (refs #79)
  CONTRIBUTORS.md
  src/main/java/com/aparapi/internal/model/ClassModel.java
  src/main/java/com/aparapi/internal/writer/KernelWriter.java
  src/test/java/com/aparapi/runtime/LocalArrayArgsIssue79Test.java
Labels: enhancement

#82 Update: Add complete suppport for OpenCL 1.2 atomics on arrays by map…
  CHANGELOG.md
  CONTRIBUTORS.md
  src/main/java/com/aparapi/Kernel.java
  src/main/java/com/aparapi/internal/kernel/KernelRunner.java
  src/main/java/com/aparapi/internal/model/ClassModel.java
  src/main/java/com/aparapi/internal/model/Entrypoint.java
  src/main/java/com/aparapi/internal/writer/KernelWriter.java
  src/test/java/com/aparapi/codegen/test/Atomic32PragmaTest.java
  src/test/java/com/aparapi/runtime/Issue81AtomicsSupportTest.java
Labels: enhancement

#83 Fix: Memory leak by not disposing kernel in unit tests of feature #79 plus code quality #81
  src/main/java/com/aparapi/internal/kernel/KernelRunner.java
  src/main/java/com/aparapi/internal/writer/KernelWriter.java
  src/test/java/com/aparapi/runtime/Issue79LocalArrayArgsTest.java
  src/test/java/com/aparapi/runtime/Issue81AtomicsSupportAdvTest.java
  src/test/java/com/aparapi/runtime/Issue81AtomicsSupportTest.java
Labels: chore

#100 Fix and Update: Fix issue #62 and provide new API for kernel profiling under multithreading (refs #62)
  CHANGELOG.md
  CONTRIBUTORS.md
  pom.xml
  src/main/java/com/aparapi/IProfileReportObserver.java
  src/main/java/com/aparapi/Kernel.java
  src/main/java/com/aparapi/ProfileReport.java
  src/main/java/com/aparapi/internal/kernel/KernelDeviceProfile.java
  src/main/java/com/aparapi/internal/kernel/KernelProfile.java
  src/main/java/com/aparapi/internal/kernel/ProfilingEvent.java
  src/test/java/com/aparapi/runtime/ProfileReportBackwardsCompatTest.java
  src/test/java/com/aparapi/runtime/ProfileReportNewAPITest.java
  src/test/java/com/aparapi/runtime/ProfileReportUnitTest.java
Labels: Bounty $$$, bug, enhancement

#110 ci(travis): fixes issue where travis fails to get codacy dependency.
  .travis.yml
  .travis/codacy-install.sh
Labels: chore

#109 test: fixed JtpRangeIdsTest to test for correct results, no longer ignored
  src/test/java/com/aparapi/runtime/JtpRangeIdsTest.java
Labels: chore
